AllCops:
  # Use Ruby 2.3 parser
  TargetRubyVersion: 2.3

Style/DotPosition:
  EnforcedStyle: trailing

ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 18

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'spec/**/*'

Style/AndOr:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_first_parameter

Style/Documentation:
  Enabled: false

Style/ExtraSpacing:
  # When true, allows most uses of extra spacing if the intent is to align
  # things with the previous or next line, not counting empty lines or comment
  # lines.
  AllowForAlignment: true

Style/LambdaCall:
  Enabled: true
  EnforcedStyle: braces

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
  SupportedStyles:
    - empty_lines
    - no_empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines
  SupportedStyles:
    - empty_lines
    - no_empty_lines

Style/EmptyLinesAroundBlockBody:
  Description: "Keeps track of empty lines around block bodies."
  Enabled: false

Style/EmptyLines:
  Description: "Don't use several empty lines in a row."
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: false

Style/EndOfLine:
  Description: 'Use Unix-style line endings.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#crlf'
  Enabled: true

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/WordArray:
  Description: 'Use %w or %W for arrays of words.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#percent-w'
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
